# Generated by Django 4.2.13 on 2024-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titw_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdept',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysdept',
            name='is_system',
            field=models.PositiveIntegerField(db_comment='是否为系统内置数据'),
        ),
        migrations.AlterField(
            model_name='sysdict',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysdict',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysdict',
            name='is_system',
            field=models.PositiveIntegerField(db_comment='是否为系统内置数据'),
        ),
        migrations.AlterField(
            model_name='sysdict',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysdictitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysdictitem',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysdictitem',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysfile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysfile',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysfile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间'),
        ),
        migrations.AlterField(
            model_name='syslog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True),
        ),
        migrations.AlterField(
            model_name='syslog',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='is_cache',
            field=models.PositiveIntegerField(blank=True, db_comment='是否缓存', null=True),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='is_external',
            field=models.PositiveIntegerField(blank=True, db_comment='是否外链', null=True),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='is_hidden',
            field=models.PositiveIntegerField(blank=True, db_comment='是否隐藏', null=True),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysmessage',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysmessageuser',
            name='is_read',
            field=models.PositiveIntegerField(db_comment='是否已读'),
        ),
        migrations.AlterField(
            model_name='sysnotice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysnotice',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysnotice',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysoption',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='is_system',
            field=models.PositiveIntegerField(db_comment='是否为系统内置数据'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysstorage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysstorage',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysstorage',
            name='is_default',
            field=models.PositiveIntegerField(db_comment='是否为默认存储'),
        ),
        migrations.AlterField(
            model_name='sysstorage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='id',
            field=models.BigAutoField(db_comment='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='is_system',
            field=models.PositiveIntegerField(db_comment='是否为系统内置数据'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='修改时间', null=True),
        ),
    ]
