# Generated by Django 4.2.13 on 2024-06-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titw_db', '0002_alter_sysdept_id_alter_sysdept_is_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='avatar',
            field=models.TextField(blank=True, db_comment='头像地址', null=True),
        ),
    ]
