# Generated by Django 4.2.13 on 2024-06-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titw_db', '0003_alter_sysuser_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sysdictitem',
            unique_together={('label', 'dict_id')},
        ),
    ]
